'use client'

import React, { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card'
import { Button } from '../../components/ui/Button'
import { useCRUDStore } from '@/lib/store/crudStore'
import { useDashboardStore } from '@/lib/store/dashboardStore'
import { FileText, Plus, Download, Eye, Calendar, User, BarChart, Trash2, X, Save, Filter } from 'lucide-react'
import toast from 'react-hot-toast'

export default function ReportsPage() {
    const { reports, addReport, deleteReport } = useCRUDStore()
    const { user, checkPermission } = useDashboardStore()
    const [isGenerating, setIsGenerating] = useState(false)
    const [typeFilter, setTypeFilter] = useState<string>('all')
    const [newReport, setNewReport] = useState({
        title: '',
        type: 'Sales'
    })

    const canCreate = checkPermission('reports.create')
    const canView = checkPermission('reports.view')

    const reportTypes = ['Sales', 'Analytics', 'Products', 'Finance', 'Users', 'Inventory', 'Performance']

    const filteredReports = reports.filter(report => {
        return typeFilter === 'all' || report.type === typeFilter
    })

    const handleGenerateReport = () => {
        if (!newReport.title) {
            toast.error('Please enter a report title')
            return
        }

        addReport({
            title: newReport.title,
            type: newReport.type,
            generatedBy: user?.name || 'System',
            date: new Date().toISOString().split('T')[0],
            size: `${Math.floor(Math.random() * 5) + 1}.${Math.floor(Math.random() * 9)} MB`
        })

        toast.success('Report generated successfully')
        setIsGenerating(false)
        setNewReport({ title: '', type: 'Sales' })
    }

    const handleDeleteReport = (id: string) => {
        if (window.confirm('Are you sure you want to delete this report?')) {
            deleteReport(id)
            toast.success('Report deleted successfully')
        }
    }

    const handleDownloadReport = (report: any) => {
        toast.success(`Downloading ${report.title}...`)

        // Simulate download
        setTimeout(() => {
            toast.success(`${report.title} downloaded successfully`)
        }, 1500)
    }

    const handleExportAll = () => {
        const exportData = filteredReports.map(report => ({
            'Report ID': report.id,
            'Title': report.title,
            'Type': report.type,
            'Generated By': report.generatedBy,
            'Date': report.date,
            'Size': report.size
        }))

        const csv = convertToCSV(exportData)
        downloadFile(csv, `reports-${new Date().toISOString().split('T')[0]}.csv`, 'text/csv')
        toast.success('Reports list exported successfully')
    }

    if (!canView) {
        return (
            <div className="p-6">
                <Card>
                    <CardContent className="p-8 text-center">
                        <FileText className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                        <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Access Denied</h2>
                        <p className="text-gray-600 dark:text-gray-400">
                            You don't have permission to access reports. Only Admin and Manager roles can view this page.
                        </p>
                    </CardContent>
                </Card>
            </div>
        )
    }

    return (
        <div className="p-4 sm:p-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Reports</h1>
                    <p className="text-gray-600 dark:text-gray-400">Generated reports and analytics</p>
                </div>
                <div className="flex items-center gap-3">
                    <Button variant="secondary" icon={<Download size={18} />} onClick={handleExportAll}>
                        Export List
                    </Button>
                    {canCreate && (
                        <Button icon={<Plus size={18} />} onClick={() => setIsGenerating(true)}>
                            Generate Report
                        </Button>
                    )}
                </div>
            </div>

            {/* Filter */}
            <Card className="mb-6">
                <CardContent className="p-4">
                    <div className="flex items-center gap-3">
                        <Filter className="text-gray-400" size={18} />
                        <select
                            value={typeFilter}
                            onChange={(e) => setTypeFilter(e.target.value)}
                            className="px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
                        >
                            <option value="all">All Report Types</option>
                            {reportTypes.map(type => (
                                <option key={type} value={type}>{type}</option>
                            ))}
                        </select>
                    </div>
                </CardContent>
            </Card>

            {/* Generate Report Form */}
            {isGenerating && (
                <Card className="mb-6 border-2 border-blue-200 dark:border-blue-800">
                    <CardHeader>
                        <CardTitle className="flex items-center justify-between">
                            <span>Generate New Report</span>
                            <button
                                onClick={() => setIsGenerating(false)}
                                className="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors"
                            >
                                <X size={20} />
                            </button>
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                    Report Title *
                                </label>
                                <input
                                    type="text"
                                    value={newReport.title}
                                    onChange={(e) => setNewReport({...newReport, title: e.target.value})}
                                    className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    placeholder="Monthly Sales Report"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                    Report Type
                                </label>
                                <select
                                    value={newReport.type}
                                    onChange={(e) => setNewReport({...newReport, type: e.target.value})}
                                    className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
                                >
                                    {reportTypes.map(type => (
                                        <option key={type} value={type}>{type}</option>
                                    ))}
                                </select>
                            </div>
                        </div>
                        <div className="mt-6 flex justify-end">
                            <Button icon={<Save size={18} />} onClick={handleGenerateReport}>
                                Generate Report
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            )}

            {/* Reports Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredReports.map((report) => (
                    <Card key={report.id} className="hover:shadow-lg transition-all duration-300 group relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-20 h-20">
                            <div className="absolute transform rotate-45 translate-x-10 translate-y-[-10px] bg-gradient-to-r from-blue-500/10 to-purple-600/10 w-28 h-10" />
                        </div>

                        <CardHeader>
                            <div className="flex items-start justify-between">
                                <div className="p-3 rounded-xl bg-gradient-to-br from-blue-500/10 to-purple-600/10">
                                    <FileText className="w-6 h-6 text-blue-600 dark:text-blue-400" />
                                </div>
                                <div className="flex items-center space-x-2">
                                    <span className="text-xs px-2 py-1 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 font-medium">
                                        {report.type}
                                    </span>
                                    {canCreate && (
                                        <button
                                            onClick={() => handleDeleteReport(report.id)}
                                            className="p-1.5 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                                        >
                                            <Trash2 size={16} />
                                        </button>
                                    )}
                                </div>
                            </div>
                            <CardTitle className="mt-4 text-lg line-clamp-1">{report.title}</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="space-y-3">
                                <div className="flex items-center text-sm text-gray-600 dark:text-gray-400">
                                    <User className="w-4 h-4 mr-2 flex-shrink-0" />
                                    <span className="truncate">Generated by: {report.generatedBy}</span>
                                </div>
                                <div className="flex items-center text-sm text-gray-600 dark:text-gray-400">
                                    <Calendar className="w-4 h-4 mr-2 flex-shrink-0" />
                                    <span>Date: {new Date(report.date).toLocaleDateString('en-US', {
                                        year: 'numeric',
                                        month: 'short',
                                        day: 'numeric'
                                    })}</span>
                                </div>
                                <div className="flex items-center text-sm text-gray-600 dark:text-gray-400">
                                    <BarChart className="w-4 h-4 mr-2 flex-shrink-0" />
                                    <span>Size: {report.size}</span>
                                </div>
                            </div>
                            <div className="flex items-center space-x-2 mt-6">
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    icon={<Eye size={16} />}
                                    className="flex-1"
                                    onClick={() => toast(`Viewing ${report.title}`, {
                                        icon: '👁️',
                                        duration: 3000
                                    })}
                                >
                                    View
                                </Button>
                                <Button
                                    variant="secondary"
                                    size="sm"
                                    icon={<Download size={16} />}
                                    className="flex-1"
                                    onClick={() => handleDownloadReport(report)}
                                >
                                    Download
                                </Button>
                            </div>
                        </CardContent>
                    </Card>
                ))}
            </div>

            {filteredReports.length === 0 && (
                <Card>
                    <CardContent className="p-12 text-center">
                        <div className="w-20 h-20 bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FileText className="w-10 h-10 text-gray-400" />
                        </div>
                        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">No Reports Found</h3>
                        <p className="text-gray-600 dark:text-gray-400 mb-6">
                            {typeFilter !== 'all'
                                ? `No ${typeFilter} reports have been generated yet.`
                                : 'No reports have been generated yet.'}
                        </p>
                        {canCreate && (
                            <Button onClick={() => setIsGenerating(true)}>
                                Generate Your First Report
                            </Button>
                        )}
                    </CardContent>
                </Card>
            )}
        </div>
    )
}

// Helper functions
function convertToCSV(data: any[]) {
    if (!data.length) return ''

    const headers = Object.keys(data[0]).join(',')
    const rows = data.map(obj =>
        Object.values(obj).map(value =>
            typeof value === 'string' ? `"${value.replace(/"/g, '""')}"` : value
        ).join(',')
    )

    return [headers, ...rows].join('\n')
}

function downloadFile(content: string, fileName: string, mimeType: string) {
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = fileName
    link.style.display = 'none'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
}